# Generated by Django 5.1.7 on 2025-03-10 23:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aits', '0002_notifications'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department_id', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('faculty', models.CharField(choices=[('computer_science', 'Computer Science'), ('software_engineering', 'Software Engineering'), ('information_technology', 'Information Technology'), ('library_and_information', 'Library And Information')], max_length=50)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='issue',
            name='category',
            field=models.CharField(choices=[('missing_mark', 'Missing Mark'), ('ask_fro_re_do', 'Ask for Re-do'), ('wrong_marks', 'Wrong Marks'), ('other', 'Other')], default='missing_mark', max_length=20),
        ),
        migrations.AlterField(
            model_name='issue',
            name='assigned_to',
            field=models.ForeignKey(blank=True, limit_choices_to={'user_type': 'lecturer'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_issues', to='aits.user'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='student',
            field=models.ForeignKey(limit_choices_to={'user_type': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='submitted_issues', to='aits.user'),
        ),
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.CharField(choices=[('computer_science', 'Computer Science'), ('software_engineering', 'Software Engineering'), ('information_technology', 'Information Technology'), ('library_and_information', 'Library And Information')], max_length=50),
        ),
    ]
