# Generated by Django 5.1.5 on 2025-03-17 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aits', '0002_alter_user_groups_alter_user_user_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='category',
            field=models.CharField(choices=[('academic', 'Academic Issues'), ('technical', 'Technical Issues'), ('administrative', 'Administrative Issues'), ('examination', 'Examination Issues'), ('registration', 'Registration Issues'), ('other', 'Other Issues')], max_length=20),
        ),
    ]
