# Generated by Django 5.1.5 on 2025-03-17 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aits', '0004_issue_priority_issue_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='courseUnit',
            field=models.CharField(blank=True, choices=[('CSC1100', 'CSC1100 - Programming Fundamentals'), ('CSC1200', 'CSC1200 - Data Structures'), ('CSC2100', 'CSC2100 - Database Systems'), ('CSC2200', 'CSC2200 - Web Development'), ('CSC3100', 'CSC3100 - Software Engineering')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='semester',
            field=models.CharField(blank=True, choices=[('1', 'Semester 1'), ('2', 'Semester 2')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='yearOfStudy',
            field=models.CharField(blank=True, choices=[('1', 'First Year'), ('2', 'Second Year'), ('3', 'Third Year'), ('4', 'Fourth Year')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='issue',
            name='priority',
            field=models.CharField(blank=True, choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='issue',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
