# Generated by Django 5.1.7 on 2025-03-12 19:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aits', '0004_remove_department_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(choices=[('computer_science', 'Computer Science'), ('software_engineering', 'Software Engineering'), ('information_technology', 'Information Technology'), ('library_and_information', 'Library And Information')], default='computer_science', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.ForeignKey(max_length=50, on_delete=django.db.models.deletion.CASCADE, to='aits.department'),
        ),
    ]
