# Generated by Django 5.1.5 on 2025-03-22 15:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aits', '0005_alter_department_name_alter_user_department'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notifications',
            old_name='user',
            new_name='recipient',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='staff_id',
            new_name='user_id',
        ),
        migrations.RemoveField(
            model_name='department',
            name='faculty',
        ),
        migrations.RemoveField(
            model_name='notifications',
            name='type',
        ),
        migrations.RemoveField(
            model_name='user',
            name='student_number',
        ),
        migrations.AddField(
            model_name='issue',
            name='courseUnit',
            field=models.CharField(blank=True, choices=[('CSC1100', 'CSC1100 - System Analysis And Design'), ('CSC1200', 'CSC1200 - Data Structures'), ('CSC2100', 'CSC2100 - Operating Systems'), ('CSC2200', 'CSC2200 - Software Development Project'), ('CSC3100', 'CSC3100 - Probability And Statistics')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='semester',
            field=models.CharField(blank=True, choices=[('1', 'Semester 1'), ('2', 'Semester 2')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='yearOfStudy',
            field=models.CharField(blank=True, choices=[('1', 'First Year'), ('2', 'Second Year'), ('3', 'Third Year'), ('4', 'Fourth Year')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='notifications',
            name='notification_type',
            field=models.CharField(choices=[('issue_created', 'New Issue Created'), ('issue_updated', 'Issue Updated'), ('issue_resolved', 'Issue Resolved'), ('issue_assigned', 'Issue Assigned')], default='issue_created', max_length=15),
        ),
        migrations.AddField(
            model_name='user',
            name='college',
            field=models.CharField(blank=True, choices=[('College of Computing', 'College of Computing'), ('College Of Humanity And Social Sciences', 'College Of Humanity And Social Sciences'), ('College Of Engineering', 'College Of Engineering'), ('College Of Education', 'College Of Education')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='course',
            field=models.CharField(blank=True, choices=[('Computer Science', 'Computer Science'), ('Software Engineering', 'Software Engineering'), ('Library and Information', 'Library and Information'), ('Information Technology', 'Information Technology')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='full_name',
            field=models.CharField(default='default_full_name', max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='year_of_study',
            field=models.CharField(blank=True, choices=[('1', 'First Year'), ('2', 'Second Year'), ('3', 'Third Year'), ('4', 'Fourth Year')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=55),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.CreateModel(
            name='AcademicRegistrar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registrar_id', models.CharField(blank=True, max_length=10, null=True)),
                ('college', models.CharField(blank=True, choices=[('College of Computing', 'College of Computing'), ('College Of Humanity And Social Sciences', 'College Of Humanity And Social Sciences'), ('College Of Engineering', 'College Of Engineering'), ('College Of Education', 'College Of Education')], max_length=100, null=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrars', to='aits.department')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='registrar_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Lecturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lecturer_id', models.CharField(blank=True, max_length=10, null=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecturers', to='aits.department')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lecturer_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_number', models.CharField(blank=True, max_length=20, null=True)),
                ('year_of_study', models.CharField(blank=True, choices=[('First Year', 'First Year'), ('Second Year', 'Second Year'), ('Third Year', 'Third Year')], max_length=20, null=True)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='aits.department')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
