# Generated by Django 5.1.5 on 2025-03-18 07:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aits', '0006_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='college',
            field=models.CharField(blank=True, choices=[('College of Computing', 'College of Computing'), ('College Of Humanity And Social Sciences', 'College Of Humanity And Social Sciences'), ('College Of Engineering', 'College Of Engineering'), ('College Of Education', 'College Of Education')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='course',
            field=models.CharField(blank=True, choices=[('Computer Science', 'Computer Science'), ('Software Engineering', 'Software Engineering'), ('Library and Information', 'Library and Information'), ('Information Technology', 'Information Technology')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='aits.department'),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(choices=[('Department of Computer Science', 'Department of Computer Science'), ('Department Of Software Engineering', 'Department Of Software Engineering'), ('Department of Library And Information System', 'Department of Library And Information System'), ('Department Of Information Technology', 'Department Of Information Technology')], max_length=100),
        ),
    ]
