# Generated by Django 5.1.5 on 2025-03-18 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aits', '0007_student_college_student_course_student_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='year_of_study',
            field=models.CharField(blank=True, choices=[('First Year', 'First Year'), ('Second Year', 'Second Year'), ('Third Year', 'Third Year')], max_length=20, null=True),
        ),
    ]
