# Generated by Django 5.1.5 on 2025-03-24 08:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aits', '0008_remove_department_id_alter_department_department_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='role',
            new_name='user_role',
        ),
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.ForeignKey(default=1, max_length=50, on_delete=django.db.models.deletion.CASCADE, to='aits.department'),
        ),
    ]
