# Generated by Django 5.1.5 on 2025-03-18 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aits', '0008_student_year_of_study'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicregistrar',
            name='college',
            field=models.CharField(blank=True, choices=[('College of Computing', 'College of Computing'), ('College Of Humanity And Social Sciences', 'College Of Humanity And Social Sciences'), ('College Of Engineering', 'College Of Engineering'), ('College Of Education', 'College Of Education')], max_length=100, null=True),
        ),
    ]
