# Generated by Django 5.1.5 on 2025-03-18 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aits', '0009_academicregistrar_college'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('registrar', 'Academic Registrar'), ('student', 'Student'), ('lecturer', 'Lecturer')], max_length=10),
        ),
    ]
