# Generated by Django 5.1.5 on 2025-03-24 09:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aits', '0009_rename_role_user_user_role_alter_user_department'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='department_id',
            new_name='id',
        ),
        migrations.RemoveField(
            model_name='student',
            name='department',
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(choices=[('computer_science', 'Computer Science'), ('software_engineering', 'Software Engineering'), ('information_technology', 'Information Technology'), ('library_and_information', 'Library And Information')], default='computer_science', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='issue',
            name='assigned_to',
            field=models.ForeignKey(blank=True, limit_choices_to={'user_role': 'lecturer'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_issues', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='issue',
            name='student',
            field=models.ForeignKey(limit_choices_to={'user_role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='submitted_issues', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notifications',
            name='related_issue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='aits.issue'),
        ),
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.ForeignKey(blank=True, max_length=50, null=True, on_delete=django.db.models.deletion.SET_NULL, to='aits.department'),
        ),
    ]
