# Generated by Django 5.1.5 on 2025-04-25 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aits', '0011_alter_user_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issue',
            old_name='issue_id',
            new_name='id',
        ),
    ]
