# Generated by Django 5.1.5 on 2025-04-28 13:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aits', '0012_rename_issue_id_issue_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={},
        ),
        migrations.RenameField(
            model_name='issue',
            old_name='id',
            new_name='issue_id',
        ),
        migrations.AddField(
            model_name='issue',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='issue_attachments/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='academicregistrar',
            name='college',
            field=models.CharField(choices=[('College of Computing', 'College of Computing'), ('College Of Humanity And Social Sciences', 'College Of Humanity And Social Sciences'), ('College Of Engineering', 'College Of Engineering'), ('College Of Education', 'College Of Education')], max_length=100),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='issue',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10),
        ),
        migrations.AlterField(
            model_name='issue',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='issue',
            name='yearOfStudy',
            field=models.CharField(blank=True, choices=[('1', 'First Year'), ('2', 'Second Year'), ('3', 'Third Year')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='student',
            name='course',
            field=models.CharField(choices=[('Computer Science', 'Computer Science'), ('Software Engineering', 'Software Engineering'), ('Library and Information', 'Library and Information'), ('Information Technology', 'Information Technology')], max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='year_of_study',
            field=models.CharField(choices=[('First Year', 'First Year'), ('Second Year', 'Second Year'), ('Third Year', 'Third Year')], max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('lecturer', 'Lecturer'), ('registrar', 'Academic Registrar')], default='student', max_length=10),
        ),
    ]
